- name: Run All Postman Collections
run: |
  shopt -s nullglob
  failed_tests=0
  for collection in *.postman_collection.json; do
    echo "✅ Running collection: $collection"
    newman run "$collection" -r html --reporter-html-export "report-$(echo "$collection" | tr ' ' '_').html" || failed_tests=$((failed_tests+1))
  done
  if [[ $failed_tests -gt 0 ]]; then
    echo "❌ Some tests failed. Exiting with error."
    exit 1
  fi
