name: Postman API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run All Postman Collections
        run: |
          shopt -s nullglob  # Avoid errors if no collections are found
          for collection in *.postman_collection.json; do
            echo "✅ Running collection: $collection"
            newman run "$collection" -r html --reporter-html-export "report-$(echo "$collection" | tr ' ' '_').html"
          done

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-reports
          path: report-*.html

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Postman API Test Results"
          body: "Attached are the latest Postman API test reports."
          from: "Postman Tests <${{ secrets.GMAIL_USERNAME }}>"
          to: "rammarshivane@gmail.com, marshivaneram9944@gmail.com"
          attachments: report-*.html
